version: "{build}"

environment:
  matrix:
    - nodejs_version: "22"
    - nodejs_version: "20"
    - nodejs_version: "18"

platform: x64

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm ci

test_script:
  - npm run typecheck
  - npm run test:node:unit

build: off
