/**
 * v2 type surface — a hand-authored, representative excerpt.
 *
 * In the finished library this is GENERATED by `scripts/api-parser.ts`
 * (one object per documented type, a discriminated `Update`, `Json<T>` aliases
 * for structured fields, and the `BotApi` method map). This excerpt covers
 * enough methods to compile and test the whole runtime; the generator scales it
 * to the full ~100-method surface (see ADR-001/002/007).
 */

import type { Json } from "../core/json.js";
import type { InputFile, FormPart } from "../core/files.js";

// ---- primitive objects (excerpt) -------------------------------------------

export type ChatId = number | string;

export interface User {
  id: number;
  is_bot: boolean;
  first_name: string;
  last_name?: string;
  username?: string;
}

export interface Chat {
  id: number;
  type: "private" | "group" | "supergroup" | "channel";
  title?: string;
  username?: string;
}

export interface MessageEntity {
  type: string;
  offset: number;
  length: number;
  url?: string;
  user?: User;
  language?: string;
  custom_emoji_id?: string;
}

export interface Message {
  message_id: number;
  from?: User;
  chat: Chat;
  date: number;
  text?: string;
  caption?: string;
  entities?: MessageEntity[];
  reply_to_message?: Message;
}

export interface CallbackQuery {
  id: string;
  from: User;
  message?: Message;
  data?: string;
}

export interface InlineQuery {
  id: string;
  from: User;
  query: string;
  offset: string;
}

export interface ChatMemberUpdated {
  chat: Chat;
  from: User;
  date: number;
}

// ---- reply markup / structured field shapes --------------------------------

export interface InlineKeyboardButton {
  text: string;
  url?: string;
  callback_data?: string;
}

export interface InlineKeyboardMarkup {
  inline_keyboard: InlineKeyboardButton[][];
}

export interface ReplyParameters {
  message_id: number;
  chat_id?: ChatId;
}

export interface LinkPreviewOptions {
  is_disabled?: boolean;
  url?: string;
  prefer_small_media?: boolean;
}

export type ParseMode = "MarkdownV2" | "HTML" | "Markdown";

/** Either an uploadable file or a plain string the API resolves (file_id / URL). */
export type InputFileOrString = InputFile | string;

// ---- the discriminated Update union ----------------------------------------

export interface UpdateBase {
  update_id: number;
}

export type Update =
  | (UpdateBase & { message: Message })
  | (UpdateBase & { edited_message: Message })
  | (UpdateBase & { channel_post: Message })
  | (UpdateBase & { edited_channel_post: Message })
  | (UpdateBase & { callback_query: CallbackQuery })
  | (UpdateBase & { inline_query: InlineQuery })
  | (UpdateBase & { my_chat_member: ChatMemberUpdated })
  | (UpdateBase & { chat_member: ChatMemberUpdated });

export type UpdateKind =
  | "message"
  | "edited_message"
  | "channel_post"
  | "edited_channel_post"
  | "callback_query"
  | "inline_query"
  | "my_chat_member"
  | "chat_member";

// ---- method param/result pairs (excerpt) -----------------------------------
//
// Structured fields are `Json<T>`: pass a builder's `.build()` or `json(value)`.

export interface GetUpdatesParams {
  offset?: number;
  limit?: number;
  timeout?: number;
  allowed_updates?: Json<UpdateKind[]>;
}

export interface SendMessageParams {
  chat_id: ChatId;
  text: string;
  parse_mode?: ParseMode;
  entities?: Json<MessageEntity[]>;
  link_preview_options?: Json<LinkPreviewOptions>;
  reply_parameters?: Json<ReplyParameters>;
  reply_markup?: Json<InlineKeyboardMarkup>;
  disable_notification?: boolean;
}

export interface SendPhotoParams {
  chat_id: ChatId;
  photo: InputFileOrString;
  caption?: string;
  caption_entities?: Json<MessageEntity[]>;
  reply_markup?: Json<InlineKeyboardMarkup>;
  disable_notification?: boolean;
}

export interface SendMediaGroupParams {
  chat_id: ChatId;
  /** Build with `mediaGroup()…build()` (carries the JSON + its file parts). */
  media: FormPart;
  disable_notification?: boolean;
}

export interface SendChatActionParams {
  chat_id: ChatId;
  action: string;
}

export interface AnswerCallbackQueryParams {
  callback_query_id: string;
  text?: string;
  show_alert?: boolean;
}

export interface SetWebhookParams {
  url: string;
  certificate?: InputFileOrString;
  secret_token?: string;
  allowed_updates?: Json<UpdateKind[]>;
  drop_pending_updates?: boolean;
}

export interface DeleteWebhookParams {
  drop_pending_updates?: boolean;
}

// ---- the generated method map ----------------------------------------------

export interface BotApi {
  getMe: (params?: Record<string, never>) => User;
  getUpdates: (params?: GetUpdatesParams) => Update[];
  sendMessage: (params: SendMessageParams) => Message;
  sendPhoto: (params: SendPhotoParams) => Message;
  sendMediaGroup: (params: SendMediaGroupParams) => Message[];
  sendChatAction: (params: SendChatActionParams) => boolean;
  answerCallbackQuery: (params: AnswerCallbackQueryParams) => boolean;
  setWebhook: (params: SetWebhookParams) => boolean;
  deleteWebhook: (params?: DeleteWebhookParams) => boolean;
}

export type MethodName = keyof BotApi;
export type ParamsOf<M extends MethodName> = Parameters<BotApi[M]>[0];
export type ResultOf<M extends MethodName> = ReturnType<BotApi[M]>;
