// biome-ignore-all lint: generated
// biome-ignore-all format: generated
// biome-ignore-all assist/source/organizeImports: generated
/** AUTO-GENERATED by scripts/api-parser.ts - DO NOT EDIT BY HAND. */
import { Transport, type TransportOptions } from "./transport.js";
import { serializeParams } from "./serialize.js";
import type * as T from "../types/index.js";

export class Api {
  protected readonly transport: Transport;

  constructor(token: string, options?: TransportOptions) {
    this.transport = new Transport(token, options);
  }

  protected request<R>(
    method: string,
    params?: Record<string, unknown>,
    signal?: AbortSignal,
  ): Promise<R> {
    return this.transport.request<R>(method, params ? serializeParams(params) : params, signal);
  }

  getUpdates(params?: T.GetUpdatesParams, signal?: AbortSignal): Promise<T.GetUpdatesResult> {
    return this.request<T.GetUpdatesResult>("getUpdates", params, signal);
  }
  setWebhook(params: T.SetWebhookParams, signal?: AbortSignal): Promise<T.SetWebhookResult> {
    return this.request<T.SetWebhookResult>("setWebhook", params, signal);
  }
  deleteWebhook(params?: T.DeleteWebhookParams, signal?: AbortSignal): Promise<T.DeleteWebhookResult> {
    return this.request<T.DeleteWebhookResult>("deleteWebhook", params, signal);
  }
  getWebhookInfo(signal?: AbortSignal): Promise<T.GetWebhookInfoResult> {
    return this.request<T.GetWebhookInfoResult>("getWebhookInfo", undefined, signal);
  }
  getMe(signal?: AbortSignal): Promise<T.GetMeResult> {
    return this.request<T.GetMeResult>("getMe", undefined, signal);
  }
  logOut(signal?: AbortSignal): Promise<T.LogOutResult> {
    return this.request<T.LogOutResult>("logOut", undefined, signal);
  }
  close(signal?: AbortSignal): Promise<T.CloseResult> {
    return this.request<T.CloseResult>("close", undefined, signal);
  }
  sendMessage(params: T.SendMessageParams, signal?: AbortSignal): Promise<T.SendMessageResult> {
    return this.request<T.SendMessageResult>("sendMessage", params, signal);
  }
  forwardMessage(params: T.ForwardMessageParams, signal?: AbortSignal): Promise<T.ForwardMessageResult> {
    return this.request<T.ForwardMessageResult>("forwardMessage", params, signal);
  }
  forwardMessages(params: T.ForwardMessagesParams, signal?: AbortSignal): Promise<T.ForwardMessagesResult> {
    return this.request<T.ForwardMessagesResult>("forwardMessages", params, signal);
  }
  copyMessage(params: T.CopyMessageParams, signal?: AbortSignal): Promise<T.CopyMessageResult> {
    return this.request<T.CopyMessageResult>("copyMessage", params, signal);
  }
  copyMessages(params: T.CopyMessagesParams, signal?: AbortSignal): Promise<T.CopyMessagesResult> {
    return this.request<T.CopyMessagesResult>("copyMessages", params, signal);
  }
  sendPhoto(params: T.SendPhotoParams, signal?: AbortSignal): Promise<T.SendPhotoResult> {
    return this.request<T.SendPhotoResult>("sendPhoto", params, signal);
  }
  sendLivePhoto(params: T.SendLivePhotoParams, signal?: AbortSignal): Promise<T.SendLivePhotoResult> {
    return this.request<T.SendLivePhotoResult>("sendLivePhoto", params, signal);
  }
  sendAudio(params: T.SendAudioParams, signal?: AbortSignal): Promise<T.SendAudioResult> {
    return this.request<T.SendAudioResult>("sendAudio", params, signal);
  }
  sendDocument(params: T.SendDocumentParams, signal?: AbortSignal): Promise<T.SendDocumentResult> {
    return this.request<T.SendDocumentResult>("sendDocument", params, signal);
  }
  sendVideo(params: T.SendVideoParams, signal?: AbortSignal): Promise<T.SendVideoResult> {
    return this.request<T.SendVideoResult>("sendVideo", params, signal);
  }
  sendAnimation(params: T.SendAnimationParams, signal?: AbortSignal): Promise<T.SendAnimationResult> {
    return this.request<T.SendAnimationResult>("sendAnimation", params, signal);
  }
  sendVoice(params: T.SendVoiceParams, signal?: AbortSignal): Promise<T.SendVoiceResult> {
    return this.request<T.SendVoiceResult>("sendVoice", params, signal);
  }
  sendVideoNote(params: T.SendVideoNoteParams, signal?: AbortSignal): Promise<T.SendVideoNoteResult> {
    return this.request<T.SendVideoNoteResult>("sendVideoNote", params, signal);
  }
  sendPaidMedia(params: T.SendPaidMediaParams, signal?: AbortSignal): Promise<T.SendPaidMediaResult> {
    return this.request<T.SendPaidMediaResult>("sendPaidMedia", params, signal);
  }
  sendMediaGroup(params: T.SendMediaGroupParams, signal?: AbortSignal): Promise<T.SendMediaGroupResult> {
    return this.request<T.SendMediaGroupResult>("sendMediaGroup", params, signal);
  }
  sendLocation(params: T.SendLocationParams, signal?: AbortSignal): Promise<T.SendLocationResult> {
    return this.request<T.SendLocationResult>("sendLocation", params, signal);
  }
  sendVenue(params: T.SendVenueParams, signal?: AbortSignal): Promise<T.SendVenueResult> {
    return this.request<T.SendVenueResult>("sendVenue", params, signal);
  }
  sendContact(params: T.SendContactParams, signal?: AbortSignal): Promise<T.SendContactResult> {
    return this.request<T.SendContactResult>("sendContact", params, signal);
  }
  sendPoll(params: T.SendPollParams, signal?: AbortSignal): Promise<T.SendPollResult> {
    return this.request<T.SendPollResult>("sendPoll", params, signal);
  }
  sendChecklist(params: T.SendChecklistParams, signal?: AbortSignal): Promise<T.SendChecklistResult> {
    return this.request<T.SendChecklistResult>("sendChecklist", params, signal);
  }
  sendDice(params: T.SendDiceParams, signal?: AbortSignal): Promise<T.SendDiceResult> {
    return this.request<T.SendDiceResult>("sendDice", params, signal);
  }
  sendMessageDraft(params: T.SendMessageDraftParams, signal?: AbortSignal): Promise<T.SendMessageDraftResult> {
    return this.request<T.SendMessageDraftResult>("sendMessageDraft", params, signal);
  }
  sendChatAction(params: T.SendChatActionParams, signal?: AbortSignal): Promise<T.SendChatActionResult> {
    return this.request<T.SendChatActionResult>("sendChatAction", params, signal);
  }
  setMessageReaction(params: T.SetMessageReactionParams, signal?: AbortSignal): Promise<T.SetMessageReactionResult> {
    return this.request<T.SetMessageReactionResult>("setMessageReaction", params, signal);
  }
  getUserProfilePhotos(params: T.GetUserProfilePhotosParams, signal?: AbortSignal): Promise<T.GetUserProfilePhotosResult> {
    return this.request<T.GetUserProfilePhotosResult>("getUserProfilePhotos", params, signal);
  }
  getUserProfileAudios(params: T.GetUserProfileAudiosParams, signal?: AbortSignal): Promise<T.GetUserProfileAudiosResult> {
    return this.request<T.GetUserProfileAudiosResult>("getUserProfileAudios", params, signal);
  }
  setUserEmojiStatus(params: T.SetUserEmojiStatusParams, signal?: AbortSignal): Promise<T.SetUserEmojiStatusResult> {
    return this.request<T.SetUserEmojiStatusResult>("setUserEmojiStatus", params, signal);
  }
  getFile(params: T.GetFileParams, signal?: AbortSignal): Promise<T.GetFileResult> {
    return this.request<T.GetFileResult>("getFile", params, signal);
  }
  banChatMember(params: T.BanChatMemberParams, signal?: AbortSignal): Promise<T.BanChatMemberResult> {
    return this.request<T.BanChatMemberResult>("banChatMember", params, signal);
  }
  unbanChatMember(params: T.UnbanChatMemberParams, signal?: AbortSignal): Promise<T.UnbanChatMemberResult> {
    return this.request<T.UnbanChatMemberResult>("unbanChatMember", params, signal);
  }
  restrictChatMember(params: T.RestrictChatMemberParams, signal?: AbortSignal): Promise<T.RestrictChatMemberResult> {
    return this.request<T.RestrictChatMemberResult>("restrictChatMember", params, signal);
  }
  promoteChatMember(params: T.PromoteChatMemberParams, signal?: AbortSignal): Promise<T.PromoteChatMemberResult> {
    return this.request<T.PromoteChatMemberResult>("promoteChatMember", params, signal);
  }
  setChatAdministratorCustomTitle(params: T.SetChatAdministratorCustomTitleParams, signal?: AbortSignal): Promise<T.SetChatAdministratorCustomTitleResult> {
    return this.request<T.SetChatAdministratorCustomTitleResult>("setChatAdministratorCustomTitle", params, signal);
  }
  setChatMemberTag(params: T.SetChatMemberTagParams, signal?: AbortSignal): Promise<T.SetChatMemberTagResult> {
    return this.request<T.SetChatMemberTagResult>("setChatMemberTag", params, signal);
  }
  banChatSenderChat(params: T.BanChatSenderChatParams, signal?: AbortSignal): Promise<T.BanChatSenderChatResult> {
    return this.request<T.BanChatSenderChatResult>("banChatSenderChat", params, signal);
  }
  unbanChatSenderChat(params: T.UnbanChatSenderChatParams, signal?: AbortSignal): Promise<T.UnbanChatSenderChatResult> {
    return this.request<T.UnbanChatSenderChatResult>("unbanChatSenderChat", params, signal);
  }
  setChatPermissions(params: T.SetChatPermissionsParams, signal?: AbortSignal): Promise<T.SetChatPermissionsResult> {
    return this.request<T.SetChatPermissionsResult>("setChatPermissions", params, signal);
  }
  exportChatInviteLink(params: T.ExportChatInviteLinkParams, signal?: AbortSignal): Promise<T.ExportChatInviteLinkResult> {
    return this.request<T.ExportChatInviteLinkResult>("exportChatInviteLink", params, signal);
  }
  createChatInviteLink(params: T.CreateChatInviteLinkParams, signal?: AbortSignal): Promise<T.CreateChatInviteLinkResult> {
    return this.request<T.CreateChatInviteLinkResult>("createChatInviteLink", params, signal);
  }
  editChatInviteLink(params: T.EditChatInviteLinkParams, signal?: AbortSignal): Promise<T.EditChatInviteLinkResult> {
    return this.request<T.EditChatInviteLinkResult>("editChatInviteLink", params, signal);
  }
  createChatSubscriptionInviteLink(params: T.CreateChatSubscriptionInviteLinkParams, signal?: AbortSignal): Promise<T.CreateChatSubscriptionInviteLinkResult> {
    return this.request<T.CreateChatSubscriptionInviteLinkResult>("createChatSubscriptionInviteLink", params, signal);
  }
  editChatSubscriptionInviteLink(params: T.EditChatSubscriptionInviteLinkParams, signal?: AbortSignal): Promise<T.EditChatSubscriptionInviteLinkResult> {
    return this.request<T.EditChatSubscriptionInviteLinkResult>("editChatSubscriptionInviteLink", params, signal);
  }
  revokeChatInviteLink(params: T.RevokeChatInviteLinkParams, signal?: AbortSignal): Promise<T.RevokeChatInviteLinkResult> {
    return this.request<T.RevokeChatInviteLinkResult>("revokeChatInviteLink", params, signal);
  }
  approveChatJoinRequest(params: T.ApproveChatJoinRequestParams, signal?: AbortSignal): Promise<T.ApproveChatJoinRequestResult> {
    return this.request<T.ApproveChatJoinRequestResult>("approveChatJoinRequest", params, signal);
  }
  declineChatJoinRequest(params: T.DeclineChatJoinRequestParams, signal?: AbortSignal): Promise<T.DeclineChatJoinRequestResult> {
    return this.request<T.DeclineChatJoinRequestResult>("declineChatJoinRequest", params, signal);
  }
  answerChatJoinRequestQuery(params: T.AnswerChatJoinRequestQueryParams, signal?: AbortSignal): Promise<T.AnswerChatJoinRequestQueryResult> {
    return this.request<T.AnswerChatJoinRequestQueryResult>("answerChatJoinRequestQuery", params, signal);
  }
  sendChatJoinRequestWebApp(params: T.SendChatJoinRequestWebAppParams, signal?: AbortSignal): Promise<T.SendChatJoinRequestWebAppResult> {
    return this.request<T.SendChatJoinRequestWebAppResult>("sendChatJoinRequestWebApp", params, signal);
  }
  setChatPhoto(params: T.SetChatPhotoParams, signal?: AbortSignal): Promise<T.SetChatPhotoResult> {
    return this.request<T.SetChatPhotoResult>("setChatPhoto", params, signal);
  }
  deleteChatPhoto(params: T.DeleteChatPhotoParams, signal?: AbortSignal): Promise<T.DeleteChatPhotoResult> {
    return this.request<T.DeleteChatPhotoResult>("deleteChatPhoto", params, signal);
  }
  setChatTitle(params: T.SetChatTitleParams, signal?: AbortSignal): Promise<T.SetChatTitleResult> {
    return this.request<T.SetChatTitleResult>("setChatTitle", params, signal);
  }
  setChatDescription(params: T.SetChatDescriptionParams, signal?: AbortSignal): Promise<T.SetChatDescriptionResult> {
    return this.request<T.SetChatDescriptionResult>("setChatDescription", params, signal);
  }
  pinChatMessage(params: T.PinChatMessageParams, signal?: AbortSignal): Promise<T.PinChatMessageResult> {
    return this.request<T.PinChatMessageResult>("pinChatMessage", params, signal);
  }
  unpinChatMessage(params: T.UnpinChatMessageParams, signal?: AbortSignal): Promise<T.UnpinChatMessageResult> {
    return this.request<T.UnpinChatMessageResult>("unpinChatMessage", params, signal);
  }
  unpinAllChatMessages(params: T.UnpinAllChatMessagesParams, signal?: AbortSignal): Promise<T.UnpinAllChatMessagesResult> {
    return this.request<T.UnpinAllChatMessagesResult>("unpinAllChatMessages", params, signal);
  }
  leaveChat(params: T.LeaveChatParams, signal?: AbortSignal): Promise<T.LeaveChatResult> {
    return this.request<T.LeaveChatResult>("leaveChat", params, signal);
  }
  getChat(params: T.GetChatParams, signal?: AbortSignal): Promise<T.GetChatResult> {
    return this.request<T.GetChatResult>("getChat", params, signal);
  }
  getChatAdministrators(params: T.GetChatAdministratorsParams, signal?: AbortSignal): Promise<T.GetChatAdministratorsResult> {
    return this.request<T.GetChatAdministratorsResult>("getChatAdministrators", params, signal);
  }
  getChatMemberCount(params: T.GetChatMemberCountParams, signal?: AbortSignal): Promise<T.GetChatMemberCountResult> {
    return this.request<T.GetChatMemberCountResult>("getChatMemberCount", params, signal);
  }
  getChatMember(params: T.GetChatMemberParams, signal?: AbortSignal): Promise<T.GetChatMemberResult> {
    return this.request<T.GetChatMemberResult>("getChatMember", params, signal);
  }
  getUserPersonalChatMessages(params: T.GetUserPersonalChatMessagesParams, signal?: AbortSignal): Promise<T.GetUserPersonalChatMessagesResult> {
    return this.request<T.GetUserPersonalChatMessagesResult>("getUserPersonalChatMessages", params, signal);
  }
  setChatStickerSet(params: T.SetChatStickerSetParams, signal?: AbortSignal): Promise<T.SetChatStickerSetResult> {
    return this.request<T.SetChatStickerSetResult>("setChatStickerSet", params, signal);
  }
  deleteChatStickerSet(params: T.DeleteChatStickerSetParams, signal?: AbortSignal): Promise<T.DeleteChatStickerSetResult> {
    return this.request<T.DeleteChatStickerSetResult>("deleteChatStickerSet", params, signal);
  }
  getForumTopicIconStickers(signal?: AbortSignal): Promise<T.GetForumTopicIconStickersResult> {
    return this.request<T.GetForumTopicIconStickersResult>("getForumTopicIconStickers", undefined, signal);
  }
  createForumTopic(params: T.CreateForumTopicParams, signal?: AbortSignal): Promise<T.CreateForumTopicResult> {
    return this.request<T.CreateForumTopicResult>("createForumTopic", params, signal);
  }
  editForumTopic(params: T.EditForumTopicParams, signal?: AbortSignal): Promise<T.EditForumTopicResult> {
    return this.request<T.EditForumTopicResult>("editForumTopic", params, signal);
  }
  closeForumTopic(params: T.CloseForumTopicParams, signal?: AbortSignal): Promise<T.CloseForumTopicResult> {
    return this.request<T.CloseForumTopicResult>("closeForumTopic", params, signal);
  }
  reopenForumTopic(params: T.ReopenForumTopicParams, signal?: AbortSignal): Promise<T.ReopenForumTopicResult> {
    return this.request<T.ReopenForumTopicResult>("reopenForumTopic", params, signal);
  }
  deleteForumTopic(params: T.DeleteForumTopicParams, signal?: AbortSignal): Promise<T.DeleteForumTopicResult> {
    return this.request<T.DeleteForumTopicResult>("deleteForumTopic", params, signal);
  }
  unpinAllForumTopicMessages(params: T.UnpinAllForumTopicMessagesParams, signal?: AbortSignal): Promise<T.UnpinAllForumTopicMessagesResult> {
    return this.request<T.UnpinAllForumTopicMessagesResult>("unpinAllForumTopicMessages", params, signal);
  }
  editGeneralForumTopic(params: T.EditGeneralForumTopicParams, signal?: AbortSignal): Promise<T.EditGeneralForumTopicResult> {
    return this.request<T.EditGeneralForumTopicResult>("editGeneralForumTopic", params, signal);
  }
  closeGeneralForumTopic(params: T.CloseGeneralForumTopicParams, signal?: AbortSignal): Promise<T.CloseGeneralForumTopicResult> {
    return this.request<T.CloseGeneralForumTopicResult>("closeGeneralForumTopic", params, signal);
  }
  reopenGeneralForumTopic(params: T.ReopenGeneralForumTopicParams, signal?: AbortSignal): Promise<T.ReopenGeneralForumTopicResult> {
    return this.request<T.ReopenGeneralForumTopicResult>("reopenGeneralForumTopic", params, signal);
  }
  hideGeneralForumTopic(params: T.HideGeneralForumTopicParams, signal?: AbortSignal): Promise<T.HideGeneralForumTopicResult> {
    return this.request<T.HideGeneralForumTopicResult>("hideGeneralForumTopic", params, signal);
  }
  unhideGeneralForumTopic(params: T.UnhideGeneralForumTopicParams, signal?: AbortSignal): Promise<T.UnhideGeneralForumTopicResult> {
    return this.request<T.UnhideGeneralForumTopicResult>("unhideGeneralForumTopic", params, signal);
  }
  unpinAllGeneralForumTopicMessages(params: T.UnpinAllGeneralForumTopicMessagesParams, signal?: AbortSignal): Promise<T.UnpinAllGeneralForumTopicMessagesResult> {
    return this.request<T.UnpinAllGeneralForumTopicMessagesResult>("unpinAllGeneralForumTopicMessages", params, signal);
  }
  answerCallbackQuery(params: T.AnswerCallbackQueryParams, signal?: AbortSignal): Promise<T.AnswerCallbackQueryResult> {
    return this.request<T.AnswerCallbackQueryResult>("answerCallbackQuery", params, signal);
  }
  answerGuestQuery(params: T.AnswerGuestQueryParams, signal?: AbortSignal): Promise<T.AnswerGuestQueryResult> {
    return this.request<T.AnswerGuestQueryResult>("answerGuestQuery", params, signal);
  }
  getUserChatBoosts(params: T.GetUserChatBoostsParams, signal?: AbortSignal): Promise<T.GetUserChatBoostsResult> {
    return this.request<T.GetUserChatBoostsResult>("getUserChatBoosts", params, signal);
  }
  getBusinessConnection(params: T.GetBusinessConnectionParams, signal?: AbortSignal): Promise<T.GetBusinessConnectionResult> {
    return this.request<T.GetBusinessConnectionResult>("getBusinessConnection", params, signal);
  }
  getManagedBotToken(params: T.GetManagedBotTokenParams, signal?: AbortSignal): Promise<T.GetManagedBotTokenResult> {
    return this.request<T.GetManagedBotTokenResult>("getManagedBotToken", params, signal);
  }
  replaceManagedBotToken(params: T.ReplaceManagedBotTokenParams, signal?: AbortSignal): Promise<T.ReplaceManagedBotTokenResult> {
    return this.request<T.ReplaceManagedBotTokenResult>("replaceManagedBotToken", params, signal);
  }
  getManagedBotAccessSettings(params: T.GetManagedBotAccessSettingsParams, signal?: AbortSignal): Promise<T.GetManagedBotAccessSettingsResult> {
    return this.request<T.GetManagedBotAccessSettingsResult>("getManagedBotAccessSettings", params, signal);
  }
  setManagedBotAccessSettings(params: T.SetManagedBotAccessSettingsParams, signal?: AbortSignal): Promise<T.SetManagedBotAccessSettingsResult> {
    return this.request<T.SetManagedBotAccessSettingsResult>("setManagedBotAccessSettings", params, signal);
  }
  setMyCommands(params: T.SetMyCommandsParams, signal?: AbortSignal): Promise<T.SetMyCommandsResult> {
    return this.request<T.SetMyCommandsResult>("setMyCommands", params, signal);
  }
  deleteMyCommands(params?: T.DeleteMyCommandsParams, signal?: AbortSignal): Promise<T.DeleteMyCommandsResult> {
    return this.request<T.DeleteMyCommandsResult>("deleteMyCommands", params, signal);
  }
  getMyCommands(params?: T.GetMyCommandsParams, signal?: AbortSignal): Promise<T.GetMyCommandsResult> {
    return this.request<T.GetMyCommandsResult>("getMyCommands", params, signal);
  }
  setMyName(params?: T.SetMyNameParams, signal?: AbortSignal): Promise<T.SetMyNameResult> {
    return this.request<T.SetMyNameResult>("setMyName", params, signal);
  }
  getMyName(params?: T.GetMyNameParams, signal?: AbortSignal): Promise<T.GetMyNameResult> {
    return this.request<T.GetMyNameResult>("getMyName", params, signal);
  }
  setMyDescription(params?: T.SetMyDescriptionParams, signal?: AbortSignal): Promise<T.SetMyDescriptionResult> {
    return this.request<T.SetMyDescriptionResult>("setMyDescription", params, signal);
  }
  getMyDescription(params?: T.GetMyDescriptionParams, signal?: AbortSignal): Promise<T.GetMyDescriptionResult> {
    return this.request<T.GetMyDescriptionResult>("getMyDescription", params, signal);
  }
  setMyShortDescription(params?: T.SetMyShortDescriptionParams, signal?: AbortSignal): Promise<T.SetMyShortDescriptionResult> {
    return this.request<T.SetMyShortDescriptionResult>("setMyShortDescription", params, signal);
  }
  getMyShortDescription(params?: T.GetMyShortDescriptionParams, signal?: AbortSignal): Promise<T.GetMyShortDescriptionResult> {
    return this.request<T.GetMyShortDescriptionResult>("getMyShortDescription", params, signal);
  }
  setMyProfilePhoto(params: T.SetMyProfilePhotoParams, signal?: AbortSignal): Promise<T.SetMyProfilePhotoResult> {
    return this.request<T.SetMyProfilePhotoResult>("setMyProfilePhoto", params, signal);
  }
  removeMyProfilePhoto(signal?: AbortSignal): Promise<T.RemoveMyProfilePhotoResult> {
    return this.request<T.RemoveMyProfilePhotoResult>("removeMyProfilePhoto", undefined, signal);
  }
  setChatMenuButton(params?: T.SetChatMenuButtonParams, signal?: AbortSignal): Promise<T.SetChatMenuButtonResult> {
    return this.request<T.SetChatMenuButtonResult>("setChatMenuButton", params, signal);
  }
  getChatMenuButton(params?: T.GetChatMenuButtonParams, signal?: AbortSignal): Promise<T.GetChatMenuButtonResult> {
    return this.request<T.GetChatMenuButtonResult>("getChatMenuButton", params, signal);
  }
  setMyDefaultAdministratorRights(params?: T.SetMyDefaultAdministratorRightsParams, signal?: AbortSignal): Promise<T.SetMyDefaultAdministratorRightsResult> {
    return this.request<T.SetMyDefaultAdministratorRightsResult>("setMyDefaultAdministratorRights", params, signal);
  }
  getMyDefaultAdministratorRights(params?: T.GetMyDefaultAdministratorRightsParams, signal?: AbortSignal): Promise<T.GetMyDefaultAdministratorRightsResult> {
    return this.request<T.GetMyDefaultAdministratorRightsResult>("getMyDefaultAdministratorRights", params, signal);
  }
  getAvailableGifts(signal?: AbortSignal): Promise<T.GetAvailableGiftsResult> {
    return this.request<T.GetAvailableGiftsResult>("getAvailableGifts", undefined, signal);
  }
  sendGift(params: T.SendGiftParams, signal?: AbortSignal): Promise<T.SendGiftResult> {
    return this.request<T.SendGiftResult>("sendGift", params, signal);
  }
  giftPremiumSubscription(params: T.GiftPremiumSubscriptionParams, signal?: AbortSignal): Promise<T.GiftPremiumSubscriptionResult> {
    return this.request<T.GiftPremiumSubscriptionResult>("giftPremiumSubscription", params, signal);
  }
  verifyUser(params: T.VerifyUserParams, signal?: AbortSignal): Promise<T.VerifyUserResult> {
    return this.request<T.VerifyUserResult>("verifyUser", params, signal);
  }
  verifyChat(params: T.VerifyChatParams, signal?: AbortSignal): Promise<T.VerifyChatResult> {
    return this.request<T.VerifyChatResult>("verifyChat", params, signal);
  }
  removeUserVerification(params: T.RemoveUserVerificationParams, signal?: AbortSignal): Promise<T.RemoveUserVerificationResult> {
    return this.request<T.RemoveUserVerificationResult>("removeUserVerification", params, signal);
  }
  removeChatVerification(params: T.RemoveChatVerificationParams, signal?: AbortSignal): Promise<T.RemoveChatVerificationResult> {
    return this.request<T.RemoveChatVerificationResult>("removeChatVerification", params, signal);
  }
  readBusinessMessage(params: T.ReadBusinessMessageParams, signal?: AbortSignal): Promise<T.ReadBusinessMessageResult> {
    return this.request<T.ReadBusinessMessageResult>("readBusinessMessage", params, signal);
  }
  deleteBusinessMessages(params: T.DeleteBusinessMessagesParams, signal?: AbortSignal): Promise<T.DeleteBusinessMessagesResult> {
    return this.request<T.DeleteBusinessMessagesResult>("deleteBusinessMessages", params, signal);
  }
  setBusinessAccountName(params: T.SetBusinessAccountNameParams, signal?: AbortSignal): Promise<T.SetBusinessAccountNameResult> {
    return this.request<T.SetBusinessAccountNameResult>("setBusinessAccountName", params, signal);
  }
  setBusinessAccountUsername(params: T.SetBusinessAccountUsernameParams, signal?: AbortSignal): Promise<T.SetBusinessAccountUsernameResult> {
    return this.request<T.SetBusinessAccountUsernameResult>("setBusinessAccountUsername", params, signal);
  }
  setBusinessAccountBio(params: T.SetBusinessAccountBioParams, signal?: AbortSignal): Promise<T.SetBusinessAccountBioResult> {
    return this.request<T.SetBusinessAccountBioResult>("setBusinessAccountBio", params, signal);
  }
  setBusinessAccountProfilePhoto(params: T.SetBusinessAccountProfilePhotoParams, signal?: AbortSignal): Promise<T.SetBusinessAccountProfilePhotoResult> {
    return this.request<T.SetBusinessAccountProfilePhotoResult>("setBusinessAccountProfilePhoto", params, signal);
  }
  removeBusinessAccountProfilePhoto(params: T.RemoveBusinessAccountProfilePhotoParams, signal?: AbortSignal): Promise<T.RemoveBusinessAccountProfilePhotoResult> {
    return this.request<T.RemoveBusinessAccountProfilePhotoResult>("removeBusinessAccountProfilePhoto", params, signal);
  }
  setBusinessAccountGiftSettings(params: T.SetBusinessAccountGiftSettingsParams, signal?: AbortSignal): Promise<T.SetBusinessAccountGiftSettingsResult> {
    return this.request<T.SetBusinessAccountGiftSettingsResult>("setBusinessAccountGiftSettings", params, signal);
  }
  getBusinessAccountStarBalance(params: T.GetBusinessAccountStarBalanceParams, signal?: AbortSignal): Promise<T.GetBusinessAccountStarBalanceResult> {
    return this.request<T.GetBusinessAccountStarBalanceResult>("getBusinessAccountStarBalance", params, signal);
  }
  transferBusinessAccountStars(params: T.TransferBusinessAccountStarsParams, signal?: AbortSignal): Promise<T.TransferBusinessAccountStarsResult> {
    return this.request<T.TransferBusinessAccountStarsResult>("transferBusinessAccountStars", params, signal);
  }
  getBusinessAccountGifts(params: T.GetBusinessAccountGiftsParams, signal?: AbortSignal): Promise<T.GetBusinessAccountGiftsResult> {
    return this.request<T.GetBusinessAccountGiftsResult>("getBusinessAccountGifts", params, signal);
  }
  getUserGifts(params: T.GetUserGiftsParams, signal?: AbortSignal): Promise<T.GetUserGiftsResult> {
    return this.request<T.GetUserGiftsResult>("getUserGifts", params, signal);
  }
  getChatGifts(params: T.GetChatGiftsParams, signal?: AbortSignal): Promise<T.GetChatGiftsResult> {
    return this.request<T.GetChatGiftsResult>("getChatGifts", params, signal);
  }
  convertGiftToStars(params: T.ConvertGiftToStarsParams, signal?: AbortSignal): Promise<T.ConvertGiftToStarsResult> {
    return this.request<T.ConvertGiftToStarsResult>("convertGiftToStars", params, signal);
  }
  upgradeGift(params: T.UpgradeGiftParams, signal?: AbortSignal): Promise<T.UpgradeGiftResult> {
    return this.request<T.UpgradeGiftResult>("upgradeGift", params, signal);
  }
  transferGift(params: T.TransferGiftParams, signal?: AbortSignal): Promise<T.TransferGiftResult> {
    return this.request<T.TransferGiftResult>("transferGift", params, signal);
  }
  postStory(params: T.PostStoryParams, signal?: AbortSignal): Promise<T.PostStoryResult> {
    return this.request<T.PostStoryResult>("postStory", params, signal);
  }
  repostStory(params: T.RepostStoryParams, signal?: AbortSignal): Promise<T.RepostStoryResult> {
    return this.request<T.RepostStoryResult>("repostStory", params, signal);
  }
  editStory(params: T.EditStoryParams, signal?: AbortSignal): Promise<T.EditStoryResult> {
    return this.request<T.EditStoryResult>("editStory", params, signal);
  }
  deleteStory(params: T.DeleteStoryParams, signal?: AbortSignal): Promise<T.DeleteStoryResult> {
    return this.request<T.DeleteStoryResult>("deleteStory", params, signal);
  }
  answerWebAppQuery(params: T.AnswerWebAppQueryParams, signal?: AbortSignal): Promise<T.AnswerWebAppQueryResult> {
    return this.request<T.AnswerWebAppQueryResult>("answerWebAppQuery", params, signal);
  }
  savePreparedInlineMessage(params: T.SavePreparedInlineMessageParams, signal?: AbortSignal): Promise<T.SavePreparedInlineMessageResult> {
    return this.request<T.SavePreparedInlineMessageResult>("savePreparedInlineMessage", params, signal);
  }
  savePreparedKeyboardButton(params: T.SavePreparedKeyboardButtonParams, signal?: AbortSignal): Promise<T.SavePreparedKeyboardButtonResult> {
    return this.request<T.SavePreparedKeyboardButtonResult>("savePreparedKeyboardButton", params, signal);
  }
  editMessageText(params?: T.EditMessageTextParams, signal?: AbortSignal): Promise<T.EditMessageTextResult> {
    return this.request<T.EditMessageTextResult>("editMessageText", params, signal);
  }
  editMessageCaption(params?: T.EditMessageCaptionParams, signal?: AbortSignal): Promise<T.EditMessageCaptionResult> {
    return this.request<T.EditMessageCaptionResult>("editMessageCaption", params, signal);
  }
  editMessageMedia(params: T.EditMessageMediaParams, signal?: AbortSignal): Promise<T.EditMessageMediaResult> {
    return this.request<T.EditMessageMediaResult>("editMessageMedia", params, signal);
  }
  editMessageLiveLocation(params: T.EditMessageLiveLocationParams, signal?: AbortSignal): Promise<T.EditMessageLiveLocationResult> {
    return this.request<T.EditMessageLiveLocationResult>("editMessageLiveLocation", params, signal);
  }
  stopMessageLiveLocation(params?: T.StopMessageLiveLocationParams, signal?: AbortSignal): Promise<T.StopMessageLiveLocationResult> {
    return this.request<T.StopMessageLiveLocationResult>("stopMessageLiveLocation", params, signal);
  }
  editMessageChecklist(params: T.EditMessageChecklistParams, signal?: AbortSignal): Promise<T.EditMessageChecklistResult> {
    return this.request<T.EditMessageChecklistResult>("editMessageChecklist", params, signal);
  }
  editMessageReplyMarkup(params?: T.EditMessageReplyMarkupParams, signal?: AbortSignal): Promise<T.EditMessageReplyMarkupResult> {
    return this.request<T.EditMessageReplyMarkupResult>("editMessageReplyMarkup", params, signal);
  }
  stopPoll(params: T.StopPollParams, signal?: AbortSignal): Promise<T.StopPollResult> {
    return this.request<T.StopPollResult>("stopPoll", params, signal);
  }
  approveSuggestedPost(params: T.ApproveSuggestedPostParams, signal?: AbortSignal): Promise<T.ApproveSuggestedPostResult> {
    return this.request<T.ApproveSuggestedPostResult>("approveSuggestedPost", params, signal);
  }
  declineSuggestedPost(params: T.DeclineSuggestedPostParams, signal?: AbortSignal): Promise<T.DeclineSuggestedPostResult> {
    return this.request<T.DeclineSuggestedPostResult>("declineSuggestedPost", params, signal);
  }
  deleteMessage(params: T.DeleteMessageParams, signal?: AbortSignal): Promise<T.DeleteMessageResult> {
    return this.request<T.DeleteMessageResult>("deleteMessage", params, signal);
  }
  deleteMessages(params: T.DeleteMessagesParams, signal?: AbortSignal): Promise<T.DeleteMessagesResult> {
    return this.request<T.DeleteMessagesResult>("deleteMessages", params, signal);
  }
  deleteMessageReaction(params: T.DeleteMessageReactionParams, signal?: AbortSignal): Promise<T.DeleteMessageReactionResult> {
    return this.request<T.DeleteMessageReactionResult>("deleteMessageReaction", params, signal);
  }
  deleteAllMessageReactions(params: T.DeleteAllMessageReactionsParams, signal?: AbortSignal): Promise<T.DeleteAllMessageReactionsResult> {
    return this.request<T.DeleteAllMessageReactionsResult>("deleteAllMessageReactions", params, signal);
  }
  sendSticker(params: T.SendStickerParams, signal?: AbortSignal): Promise<T.SendStickerResult> {
    return this.request<T.SendStickerResult>("sendSticker", params, signal);
  }
  getStickerSet(params: T.GetStickerSetParams, signal?: AbortSignal): Promise<T.GetStickerSetResult> {
    return this.request<T.GetStickerSetResult>("getStickerSet", params, signal);
  }
  getCustomEmojiStickers(params: T.GetCustomEmojiStickersParams, signal?: AbortSignal): Promise<T.GetCustomEmojiStickersResult> {
    return this.request<T.GetCustomEmojiStickersResult>("getCustomEmojiStickers", params, signal);
  }
  uploadStickerFile(params: T.UploadStickerFileParams, signal?: AbortSignal): Promise<T.UploadStickerFileResult> {
    return this.request<T.UploadStickerFileResult>("uploadStickerFile", params, signal);
  }
  createNewStickerSet(params: T.CreateNewStickerSetParams, signal?: AbortSignal): Promise<T.CreateNewStickerSetResult> {
    return this.request<T.CreateNewStickerSetResult>("createNewStickerSet", params, signal);
  }
  addStickerToSet(params: T.AddStickerToSetParams, signal?: AbortSignal): Promise<T.AddStickerToSetResult> {
    return this.request<T.AddStickerToSetResult>("addStickerToSet", params, signal);
  }
  setStickerPositionInSet(params: T.SetStickerPositionInSetParams, signal?: AbortSignal): Promise<T.SetStickerPositionInSetResult> {
    return this.request<T.SetStickerPositionInSetResult>("setStickerPositionInSet", params, signal);
  }
  deleteStickerFromSet(params: T.DeleteStickerFromSetParams, signal?: AbortSignal): Promise<T.DeleteStickerFromSetResult> {
    return this.request<T.DeleteStickerFromSetResult>("deleteStickerFromSet", params, signal);
  }
  replaceStickerInSet(params: T.ReplaceStickerInSetParams, signal?: AbortSignal): Promise<T.ReplaceStickerInSetResult> {
    return this.request<T.ReplaceStickerInSetResult>("replaceStickerInSet", params, signal);
  }
  setStickerEmojiList(params: T.SetStickerEmojiListParams, signal?: AbortSignal): Promise<T.SetStickerEmojiListResult> {
    return this.request<T.SetStickerEmojiListResult>("setStickerEmojiList", params, signal);
  }
  setStickerKeywords(params: T.SetStickerKeywordsParams, signal?: AbortSignal): Promise<T.SetStickerKeywordsResult> {
    return this.request<T.SetStickerKeywordsResult>("setStickerKeywords", params, signal);
  }
  setStickerMaskPosition(params: T.SetStickerMaskPositionParams, signal?: AbortSignal): Promise<T.SetStickerMaskPositionResult> {
    return this.request<T.SetStickerMaskPositionResult>("setStickerMaskPosition", params, signal);
  }
  setStickerSetTitle(params: T.SetStickerSetTitleParams, signal?: AbortSignal): Promise<T.SetStickerSetTitleResult> {
    return this.request<T.SetStickerSetTitleResult>("setStickerSetTitle", params, signal);
  }
  setStickerSetThumbnail(params: T.SetStickerSetThumbnailParams, signal?: AbortSignal): Promise<T.SetStickerSetThumbnailResult> {
    return this.request<T.SetStickerSetThumbnailResult>("setStickerSetThumbnail", params, signal);
  }
  setCustomEmojiStickerSetThumbnail(params: T.SetCustomEmojiStickerSetThumbnailParams, signal?: AbortSignal): Promise<T.SetCustomEmojiStickerSetThumbnailResult> {
    return this.request<T.SetCustomEmojiStickerSetThumbnailResult>("setCustomEmojiStickerSetThumbnail", params, signal);
  }
  deleteStickerSet(params: T.DeleteStickerSetParams, signal?: AbortSignal): Promise<T.DeleteStickerSetResult> {
    return this.request<T.DeleteStickerSetResult>("deleteStickerSet", params, signal);
  }
  sendRichMessage(params: T.SendRichMessageParams, signal?: AbortSignal): Promise<T.SendRichMessageResult> {
    return this.request<T.SendRichMessageResult>("sendRichMessage", params, signal);
  }
  sendRichMessageDraft(params: T.SendRichMessageDraftParams, signal?: AbortSignal): Promise<T.SendRichMessageDraftResult> {
    return this.request<T.SendRichMessageDraftResult>("sendRichMessageDraft", params, signal);
  }
  answerInlineQuery(params: T.AnswerInlineQueryParams, signal?: AbortSignal): Promise<T.AnswerInlineQueryResult> {
    return this.request<T.AnswerInlineQueryResult>("answerInlineQuery", params, signal);
  }
  sendInvoice(params: T.SendInvoiceParams, signal?: AbortSignal): Promise<T.SendInvoiceResult> {
    return this.request<T.SendInvoiceResult>("sendInvoice", params, signal);
  }
  createInvoiceLink(params: T.CreateInvoiceLinkParams, signal?: AbortSignal): Promise<T.CreateInvoiceLinkResult> {
    return this.request<T.CreateInvoiceLinkResult>("createInvoiceLink", params, signal);
  }
  answerShippingQuery(params: T.AnswerShippingQueryParams, signal?: AbortSignal): Promise<T.AnswerShippingQueryResult> {
    return this.request<T.AnswerShippingQueryResult>("answerShippingQuery", params, signal);
  }
  answerPreCheckoutQuery(params: T.AnswerPreCheckoutQueryParams, signal?: AbortSignal): Promise<T.AnswerPreCheckoutQueryResult> {
    return this.request<T.AnswerPreCheckoutQueryResult>("answerPreCheckoutQuery", params, signal);
  }
  getMyStarBalance(signal?: AbortSignal): Promise<T.GetMyStarBalanceResult> {
    return this.request<T.GetMyStarBalanceResult>("getMyStarBalance", undefined, signal);
  }
  getStarTransactions(params?: T.GetStarTransactionsParams, signal?: AbortSignal): Promise<T.GetStarTransactionsResult> {
    return this.request<T.GetStarTransactionsResult>("getStarTransactions", params, signal);
  }
  refundStarPayment(params: T.RefundStarPaymentParams, signal?: AbortSignal): Promise<T.RefundStarPaymentResult> {
    return this.request<T.RefundStarPaymentResult>("refundStarPayment", params, signal);
  }
  editUserStarSubscription(params: T.EditUserStarSubscriptionParams, signal?: AbortSignal): Promise<T.EditUserStarSubscriptionResult> {
    return this.request<T.EditUserStarSubscriptionResult>("editUserStarSubscription", params, signal);
  }
  setPassportDataErrors(params: T.SetPassportDataErrorsParams, signal?: AbortSignal): Promise<T.SetPassportDataErrorsResult> {
    return this.request<T.SetPassportDataErrorsResult>("setPassportDataErrors", params, signal);
  }
  sendGame(params: T.SendGameParams, signal?: AbortSignal): Promise<T.SendGameResult> {
    return this.request<T.SendGameResult>("sendGame", params, signal);
  }
  setGameScore(params: T.SetGameScoreParams, signal?: AbortSignal): Promise<T.SetGameScoreResult> {
    return this.request<T.SetGameScoreResult>("setGameScore", params, signal);
  }
  getGameHighScores(params: T.GetGameHighScoresParams, signal?: AbortSignal): Promise<T.GetGameHighScoresResult> {
    return this.request<T.GetGameHighScoresResult>("getGameHighScores", params, signal);
  }
}
